# Generated by Django 4.2.13 on 2024-05-17 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Letter_document', models.FileField(blank=True, null=True, upload_to='CL_Documents/')),
                ('upload_date', models.DateField(auto_now_add=True, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_CoverLetter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoverLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CL_template_Pdf', models.FileField(blank=True, null=True, upload_to='CL_Template/Pdf/')),
                ('CL_template_Word', models.FileField(blank=True, null=True, upload_to='CL_Template/Word')),
                ('IsPaid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeepgramLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('models_names', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlashCardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GreetingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='propilottemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(default='0.5', max_length=255)),
                ('verbosity', models.CharField(blank=True, default='medium', max_length=255, null=True)),
                ('transcription_delay', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CV_template_Pdf', models.FileField(blank=True, null=True, upload_to='CV_Template/Pdf/')),
                ('CV_template_Word', models.FileField(blank=True, null=True, upload_to='CV_Template/Word/')),
                ('IsPaid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SetGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default='null', max_length=500, null=True)),
                ('company_name', models.CharField(blank=True, default='null', max_length=500, null=True)),
                ('location', models.CharField(blank=True, default='null', max_length=500, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_Set_Goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('isPaid', models.BooleanField(default=False)),
                ('userId', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_resume', models.TextField(blank=True, null=True)),
                ('latest_goal', models.TextField()),
                ('latest_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SettingsLauncherpropilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewtime', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_set', to='CoWinApp.setgoals')),
                ('goals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propilot_settings', to='CoWinApp.setgoals')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_set', to='CoWinApp.setgoals')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CV_document', models.FileField(blank=True, null=True, upload_to='CV_Documents/')),
                ('upload_date', models.DateField(auto_now_add=True, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_CV', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL)),
                ('users_referred', models.ManyToManyField(related_name='referred_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProPilotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbosity', models.TextField(blank=True, null=True)),
                ('deepgram_language', models.TextField(blank=True, null=True)),
                ('programming_language', models.TextField(blank=True, null=True)),
                ('tran_delay', models.TextField(blank=True, null=True)),
                ('propilot_temp', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProPilotLauncher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('cover_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.coverletter')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.setgoals')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.resumecv')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pro_Pilot_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreeMockInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InterviewTime', models.DateTimeField(blank=True, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.setgoals')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FreeMockInterviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlashCardSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.flashcardcategory')),
            ],
        ),
        migrations.CreateModel(
            name='FlashCardInterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, default='null', max_length=500, null=True)),
                ('answer', models.TextField(blank=True, default='null', max_length=1000, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.flashcardcategory')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.flashcardsubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='AiProPilotLauncher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('cover_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.coverletter')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.setgoals')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.resumecv')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ai_Pro_Pilot_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AiInterviewProPilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InterviewTime', models.DateTimeField(blank=True, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.setgoals')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AiInterviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AiCodingMathsProPilotLauncher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_goal', models.TextField(blank=True, null=True)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('cover_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.coverletter')),
                ('programing_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.setgoals')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.resumecv')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AiCodingMaths_Pro_Pilot_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AiCodingMaths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsActive', models.BooleanField(default=True)),
                ('goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.setgoals')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ai_Coding_Maths', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
