# Generated by Django 4.2.13 on 2024-05-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoWinApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreetingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
