# Generated by Django 4.2.13 on 2024-05-17 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoWinApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aipropilotlauncher',
            name='cover_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.coverletter'),
        ),
    ]
