# Generated by Django 4.2.13 on 2024-05-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoWinApp', '0002_alter_aipropilotlauncher_cover_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingslauncherpropilot',
            name='interviewtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
