# Generated by Django 4.2.13 on 2024-05-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoWinApp', '0002_greetingmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greetingmessage',
            name='time_of_day',
        ),
    ]
