# Generated by Django 4.2.13 on 2024-05-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoWinApp', '0003_alter_settingslauncherpropilot_interviewtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingslauncherpropilot',
            name='company',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='settingslauncherpropilot',
            name='goals',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='settingslauncherpropilot',
            name='position',
            field=models.CharField(max_length=500),
        ),
    ]
