# Generated by Django 4.2.10 on 2024-03-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoWinApp', '0006_setgoals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SetGoals',
        ),
    ]
