# Generated by Django 4.2.13 on 2024-05-14 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CoWinApp', '0006_deepgramlanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProPilotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbosity', models.TextField(blank=True, null=True)),
                ('deepgram_language', models.TextField(blank=True, null=True)),
                ('programming_language', models.TextField(blank=True, null=True)),
                ('tran_delay', models.TextField(blank=True, null=True)),
                ('propilot_temp', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
