# Generated by Django 4.2.13 on 2024-05-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoWinApp', '0008_deepgramlanguage_models_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='propilottemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=255)),
                ('verbosity', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
