# Generated by Django 4.2.10 on 2024-03-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoWinApp', '0008_setgoals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setgoals',
            old_name='isActive',
            new_name='isArchived',
        ),
    ]
