# Generated by Django 4.2.11 on 2024-03-25 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoWinApp', '0011_aicategory_aisubcategory_flashcardinterviewquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisubcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.aicategory'),
        ),
        migrations.AlterField(
            model_name='flashcardinterviewquestion',
            name='answer',
            field=models.TextField(blank=True, default='null', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flashcardinterviewquestion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.aicategory'),
        ),
        migrations.AlterField(
            model_name='flashcardinterviewquestion',
            name='question',
            field=models.CharField(blank=True, default='null', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='flashcardinterviewquestion',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CoWinApp.aisubcategory'),
        ),
    ]
