# Generated by Django 4.2.11 on 2024-04-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoWinApp', '0013_users_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
